name: Build, Dockerize, and Deploy React App to Azure Static Web App

on: 
  push: 
    branches:
      - main  # Deploy changes to the main branch

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with: 
        login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/react-app:${{ github.sha }} .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }} .

    # Push Docker image to Azure Container Registry
    - name: Push Docker Image to ACR
      run: |
        docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/react-app:${{ github.sha }}

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }}

    # Deploy to Azure Static Web App platform
    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with: 
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN }}
        app_location: "/"
        api_location: null
        output_location: "/build"
