name: Build, Dockerize, and Deploy React App to Azure Satic Web App

on: 
  push: 
     branches:
        - main #deploy changes to main group


jobs: 
  build-and-deploy:
     runs-on: ubuntu-latest


     steps:
     # checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
       
       #set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # log in to azure  container registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with: 
           login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
           username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
           password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}


      # login to docker hub  
      - name: Log in to Docker Hub
        action: docker/login-actio@v2
        with: 
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}   


      # builf the docker image
      - name: Build Docker image
        run: |
            docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/react-app:${{ github.sha }} .
            docker build -t ${{ secrets.DOCKER_USERNAME }} /react-app:${{ github.sha }} .

       # push Docker image to Azure container registry
      - name: Push Docker Image to ACR
        run: |
            docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/react-app:${{ github.sha }}
       # push image to docker hub
      - name: Push Docker image to Docker Hub
        run: |
            docker push ${{ ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }} .}}      
     #deploy to Azure static web app using the image
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with: 
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN }}
           app_location: "/"
           api_loccation: null
           outpu_location: "/buld"

